export * from './areaController';
export * from './authenController';
export * from './personelController';
export * from './schoolController';
export * from './settingController';
export * from './standardcodeController';
export * from './teacherController';
export * from './uploadController';
export * from './userController';